# Работа с библиотекой numpy

### 1. Работа с массивами

In [35]:
from numpy import array

array([2, 1, 3])

array([2, 1, 3])

In [36]:
array([
    [2, -1],
    [-1, 3]
])

array([[ 2, -1],
       [-1,  3]])

In [37]:
from numpy import arange, zeros, ones, identity, diagonal, trace, argmax, argmin

arange(2, 10, 2)

array([2, 4, 6, 8])

In [38]:
zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
A = array([
    [4, -2, 1],
    [-1, 4, -2],
    [1, -1, 3]
])

A

array([[ 4, -2,  1],
       [-1,  4, -2],
       [ 1, -1,  3]])

In [42]:
diagonal(A)

array([4, 4, 3])

In [43]:
diagonal(A, 1)

array([-2, -2])

In [44]:
diagonal(A, -1)

array([-1, -1])

In [45]:
trace(A)

11

In [46]:
argmin(A, axis=0)

array([1, 0, 1], dtype=int64)

In [47]:
argmax(A, axis=1)

array([0, 1, 2], dtype=int64)

In [48]:
b = array([1, 4, 3])

b

array([1, 4, 3])

In [49]:
argmax(b)

1

### 2. Чтение и изменение элементов массива

In [50]:
a = zeros((3, 3))

a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
a[0] = [2, 3, 2]

a

array([[2., 3., 2.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
a[1, 1] = 5

a

array([[2., 3., 2.],
       [0., 5., 0.],
       [0., 0., 0.]])

In [53]:
a[2, 0:2] = [8, -3]

a

array([[ 2.,  3.,  2.],
       [ 0.,  5.,  0.],
       [ 8., -3.,  0.]])

In [54]:
a[0:2, 1] = [1, 1]

a

array([[ 2.,  1.,  2.],
       [ 0.,  1.,  0.],
       [ 8., -3.,  0.]])

### 3. Операции над массивами

In [55]:
a = array([0, 4, 9, 16])

a / 16

array([0.    , 0.25  , 0.5625, 1.    ])

In [56]:
a - 4

array([-4,  0,  5, 12])

In [57]:
from numpy import sqrt, sin

a = array([1, 4, 9, 16])

sqrt(a)

array([1., 2., 3., 4.])

In [58]:
sin(a)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332])

### 4. Скалярное произведение двух векторов

$$
    x^T \cdot y = 
    \begin{bmatrix}
        x_1 & x_2 & x_3
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
        y_1 \\
        y_2 \\
        y_3
    \end{bmatrix}
    =
    x_1y_1 + x_2y_2 + x_3y_3
$$

In [59]:
from numpy import dot

x = array([7, 3, 1])
y = array([2, 1, 2])

dot(x, y)

19

### 5. Произведение матрицы на вектор

$$
    A \cdot x = 
    \begin{bmatrix}
        a_{11} & a_{12} \\
        a_{21} & a_{22}
    \end{bmatrix}
    \begin{bmatrix}
        x_1 \\
        x_2
    \end{bmatrix}
    =
    \begin{bmatrix}
        a_{11}x_1 + a_{12}x_2 \\
        a_{21}x_1 + a_{22}x_2
    \end{bmatrix}    
$$

In [60]:
A = array([
    [1, 2],
    [3, 2]
])

A

array([[1, 2],
       [3, 2]])

In [61]:
x = array([7, 3])

x

array([7, 3])

In [62]:
dot(A, x)

array([13, 27])

### 6. Произведение матрицы на матрицу

$$
    A \cdot B = 
    \begin{bmatrix}
        a_{11} & a_{12} \\
        a_{21} & a_{22}
    \end{bmatrix}
    \begin{bmatrix}
        b_{11} & b_{12} \\
        b_{21} & b_{22}
    \end{bmatrix}
    =
    \begin{bmatrix}
        a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} \\
        a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22}
    \end{bmatrix}    
$$

In [63]:
B = array([
    [1, 1],
    [2, 2]
])

dot(A, B)

array([[5, 5],
       [7, 7]])

### 7. Векторизация

$$
    \sum_{i=0}^{100} \sqrt{\frac{i\pi}{100}} sin(\frac{i\pi}{100})
$$

In [64]:
from math import pi

x = arange(0, 1.01*pi, 0.01*pi)

dot(sqrt(x), sin(x))

77.51389798916512